# Generated by Django 2.0.9 on 2018-11-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20181112_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmembers',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name of User'),
        ),
    ]
