# Generated by Django 2.0.9 on 2018-11-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20181112_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Title'),
        ),
    ]
