# Generated by Django 2.0.9 on 2018-11-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20181112_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='type_of_update',
            field=models.CharField(choices=[('C', 'Clinical'), ('B', 'Business and Funding'), ('T', 'Technology')], max_length=1, verbose_name='Update'),
        ),
    ]
