# Generated by Django 2.0.9 on 2018-11-28 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_updates_publication_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(upload_to='')),
                ('company_name', models.CharField(max_length=250, verbose_name='Name of Company')),
                ('company_description', models.CharField(max_length=1000, verbose_name='Company Description')),
                ('company_link', models.URLField()),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.RemoveField(
            model_name='career',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='career',
            name='company_link',
        ),
        migrations.RemoveField(
            model_name='career',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='career',
            name='company_name',
        ),
        migrations.AddField(
            model_name='career',
            name='career_location',
            field=models.CharField(blank=True, max_length=250, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='career',
            name='career_role',
            field=models.CharField(default='Blah blah', max_length=250, verbose_name='Position'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='updates',
            name='publication_date',
            field=models.DateField(default=datetime.date(2018, 11, 28), verbose_name='Date'),
        ),
    ]
