# Generated by Django 2.0.9 on 2018-11-28 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20181128_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.Company'),
            preserve_default=False,
        ),
    ]
