# Generated by Django 2.0.9 on 2018-11-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_career_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmembers',
            name='team_department',
            field=models.CharField(default='NA', max_length=100, verbose_name='Team Department'),
            preserve_default=False,
        ),
    ]
