# Generated by Django 2.0.9 on 2018-12-24 05:58

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20181128_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1808', 'Fall 2018'), ('1901', 'Spring 2019'), ('1906', 'Summer 2019'), ('1908', 'Fall 2019'), ('2001', 'Spring 2020')], max_length=1, verbose_name='Term')),
                ('date_location', tinymce.models.HTMLField(verbose_name='Date & Location')),
                ('description', tinymce.models.HTMLField(verbose_name='Presentation')),
                ('recap', tinymce.models.HTMLField(blank=True, verbose_name='Recap')),
            ],
        ),
        migrations.AlterField(
            model_name='updates',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='updates',
            name='publication_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
